### ISSUE TITLE
[Bug] Repeated object in the object table

### ISSUE THREAD

**Issue by fforster** [alercebroker/alerce_client#16]
**Describe the bug**
alerce.query_objects(oid="ZTF18aahvndq", format='pandas') returns two rows, which differ by class and probabillty

**Expected behavior**
Only one row should be returned

**Additional context**
Either fix the problem or remove the columns class, classifier and probability from object.

**Comment by dirodriguezm** [comment]
This should be fixed now if the query includes the classifier parameter.
