### ISSUE TITLE
[programming] Downloading multiple light curves API

### ISSUE THREAD

**Issue by dharmesh1007** [alercebroker/alerce_client#19]
Hi,

I'm doing some major data mining and I was wondering what is the best way to download many (100s to 1000s) of light curves from Alerce using the API. I have thought about looping the alerce.query_detections function, but I would rather ask before taxing your server.

Cheers

Dharmesh Mistry

**Comment by JavierArredondo** [comment]
Hi @dharmesh1007, thanks for user our client!

We don't have a fast way to query/get the lightcurves via alerce client 😕 If you know PSQL syntax, you could access to our database via public credentials (https://github.com/alercebroker/usecases/blob/master/alercereaduser_v4.json).

We indexed some tables by `candid` and `oid`. 

If you want to use the alerce client with a loop, just do it. But can be slow for you. If you do a small script that query our database in batches of 10-100 `oid` to table `detection` can be faster that client.

Cheers.

**Comment by JavierArredondo** [comment]
@dharmesh1007,
Currently we haven't a cache for the API requests. But you can use our database or save locally the results for your queries. I will open a ticket for your request, maybe use a cache is a great solution for search popular lightcurves.

**Comment by JavierArredondo** [comment]
Hi @dharmesh1007, how are you? 

were you able to download the light curves you needed?

**Comment by dharmesh1007** [comment]
Hi @JavierArredondo, I'm good thanks!

I've tested the looping with a few dozen targets and it works great. I've no problem doing it this way. I'm sure it will be ok for several hundred or a few thousand as I am just looking to build a dataset.

Cheers
