### ISSUE TITLE
update library dependencies

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/alerce_client#2]
I cannot install alerce at present because it requires old libraries that conflict with various other programs I have. This absolutely needs to be fixed before public release. Ideally, this should be more flexible to versions. Or alternately provide complete docker-like environment.

**Comment by franzebauer** [comment]
for example....
ERROR: -python 7.12.0 has requirement prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.18 which is incompatible.
ERROR: xarray 0.15.0 has requirement pandas>=0.25, but you'll have pandas 0.24.2 which is incompatible.
ERROR: specutils 1.0 has requirement astropy>=4.0, but you'll have astropy 3.2.1 which is incompatible.
ERROR: gwcs 0.13.0 has requirement astropy>=4.0, but you'll have astropy 3.2.1 which is incompatible.
Installing collected packages: prompt-toolkit, ipython, astropy, requests, numpydoc, pandas, alerce
  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 3.0.5
    Uninstalling prompt-toolkit-3.0.5:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: 'RECORD'
Consider using the `--user` option or check the permissions.

**Comment by cvalenzu** [comment]
@franzebauer can you send your environment ( run `pip freeze` ) to replicate the error. 

And also check the best range of verson for some packages.

**Comment by franzebauer** [comment]
alabaster==0.7.12
alembic==1.4.1
anaconda-client==1.7.2
anaconda-navigator==1.9.7
appdirs==1.4.3
appnope==0.1.0
asdf==2.6.0
asteval==0.9.18
astrometry-azel==1.2.5
astropy==4.0.1
astropy-healpix==0.5
astroquery==0.4
attrs==19.3.0
Babel==2.8.0
backcall==0.2.0
backports.functools-lru-cache==1.6.1
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.9.1
bleach==3.1.5
brotlipy==0.7.0
Cartopy==0.17.0
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
clyent==1.2.2
conda==4.8.3
conda-build==3.18.11
conda-package-handling==1.7.0
conda-verify==3.4.2
cryptography==2.9.2
cycler==0.10.0
dataset==1.2.3
decorator==4.4.2
defusedxml==0.6.0
docutils==0.16
dustmaps==1.0.4
entrypoints==0.3
extinction==0.4.2
filelock==3.0.12
fitsio==1.1.1
fs==2.4.11
future==0.18.2
glob2==0.7
gwcs==0.13.0
h5py==2.10.0
healpy==1.13.0
hips==0.2
html5lib==1.0.1
httplib2==0.17.0
idna==2.8
imageio==2.8.0
imagesize==1.2.0
imbalanced-learn==0.6.2
imblearn==0.0
importlib-metadata @ file:///opt/concourse/worker/volumes/live/84197498-cbc0-4436-7ce0-03c4490b7a28/volume/importlib-metadata_1593446431408/work
ipyaladin==0.1.7
ipykernel @ file:///opt/concourse/worker/volumes/live/d654d7d0-7a76-45d4-7a77-21259603748d/volume/ipykernel_1595347267440/work/dist/ipykernel-5.3.3-py3-none-any.whl
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi @ file:///opt/concourse/worker/volumes/live/114a62c0-dd60-4a40-6382-85abb31b5f6e/volume/jedi_1592841953086/work
Jinja2==2.11.2
joblib==0.14.1
json5==0.9.2
jsonschema==3.2.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1594826976318/work
jupyter-core==4.6.3
jupyterlab==2.0.1
jupyterlab-server @ file:///tmp/build/80754af9/jupyterlab_server_1594164409481/work
keyring==21.1.1
kiwisolver==1.2.0
libarchive-c==2.9
lief==0.10.1
lmfit==1.0.1
Mako==1.1.2
MarkupSafe==1.1.1
matplotlib==3.2.0
matplotlib-venn==0.11.5
mimeparse==0.1.3
mistune==0.8.4
mkl-fft==1.1.0
mkl-random==1.1.1
mkl-service==2.3.0
mpdaf==3.4
mpmath==1.1.0
navigator-updater==0.2.1
nbconvert==5.6.1
nbformat==5.0.7
networkx==2.4
noaodatalab==2.18.6
notebook==6.0.3
numpy==1.18.5
numpydoc==0.9.2
olefile==0.46
OWSLib==0.19.1
P4J==0.27
packaging==20.4
pandas==1.0.3
pandocfilters==1.4.2
parso==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
pkgconfig==1.5.1
pkginfo==1.5.0.1
progressbar2==3.50.0
prometheus-client==0.8.0
prompt-toolkit==3.0.5
psutil==5.7.0
psycopg2-binary==2.8.4
ptyprocess==0.6.0
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pyepsg==0.4.0
pyFFTW==0.12.0
Pygments==2.6.1
pykdtree==1.3.1
pylenstool==0.1
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
pyparsing==2.4.7
pypi==2.1
pyproj==2.5.0
PyQt5==5.14.1
PyQt5-sip==12.7.1
PyQtWebEngine==5.14.0
pyrsistent==0.16.0
pyshp==2.1.0
PySocks==1.7.1
pyspeckit==0.1.23
python-dateutil==2.8.1
python-editor==1.0.4
python-utils==2.4.0
pytz==2020.1
pyvo==1.0
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.0
qtconsole==4.7.1
QtPy==1.9.0
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
ruamel-yaml==0.15.87
ruamel.yaml.clib==0.2.0
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy @ file:///opt/concourse/worker/volumes/live/14622691-c324-4e90-5a99-87aced91207b/volume/scipy_1592930535761/work
semantic-version==2.8.5
Send2Trash==1.5.0
Shapely==1.7.0
simplegeneric==0.8.1
sip-tpv==1.1
six==1.15.0
sklearn==0.0
snowballstemmer==2.0.0
soupsieve==2.0
source-inspector==0.9.dev2+gbe4e85f.d20191211
specutils==1.0
Sphinx==2.4.4
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
SQLAlchemy==1.3.15
sympy==1.6
sysrsync==0.2.1
terminado==0.8.3
testpath==0.4.4
toml==0.10.0
tornado==6.0.4
tqdm==4.43.0
tractor===git
traitlets==4.3.3
typed-ast==1.4.1
uncertainties==3.1.2
urllib3==1.25.9
venn==0.1.3
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
widgetsnbextension==3.5.1
xarray==0.15.0
zipp==3.1.0
zogy==0.8

**Comment by cvalenzu** [comment]
Thanks, i'll check them out

**Comment by cvalenzu** [comment]
We simplified the requirements in the new version (1.0.1) now it should work.
