### ISSUE TITLE
*programming* How do I get the Object ID giving RA and Dec (for example, with catshtm_conesearch(ra, dec, radius)? ) 

### ISSUE THREAD

**Issue by cosmiccandice** [alercebroker/alerce_client#21]
I'm trying to use the API to input the RA and Dec of an object and return the OID. 

For example, when using,

`alerce.catshtm_conesearch(ra, dec, radius)`

 it returns a lot of information that includes the flux, distance, catalog name, etc, but I can't find a way for it to return the OID. Is there a way to do that with this methodI? Is there another method I can use to get this? 

Thanks!

**Comment by JavierArredondo** [comment]
Hi @cosmiccandice,

You can use this snippet of code to get the ZTF objects (with their `oid`).

```python
dataframe = alerce.query_objects(
  ra=60.275177,
  dec=49.811786, 
  radius=1.5,
  format="pandas"
)
```

When you use the method `.catshtm_conesearch(ra, dec, radius)` [you get information about registered objects](https://alerce.readthedocs.io/en/latest/tutorials/xmatch_api.html) in [external catalogs](https://github.com/alercebroker/alerce_client/blob/9ac3b318b7794c1ba30e6c787b17c3b87ad8527b/alerce/crossmatch.py#L9-L16) and that information is meant to be use to perform crossmatch with ZTF alerts.

**Comment by cosmiccandice** [comment]
Wow. Very simple. Thank you, Javier!

**Comment by JavierArredondo** [comment]
You are welcome @cosmiccandice. Thanks for use our tools! 🥇
