### ISSUE TITLE
[Question] TDE classification API

### ISSUE THREAD

**Issue by LydiaMak** [alercebroker/alerce_client#43]
Hi,

I wanted to ask if TDE classification is available through API and if it is available for transients older than 2024.

Thank you,
Lydia

**Comment by ignacioreyes** [comment]
Hi!
Yes, it's possible. For example:
```python
from alerce.core import Alerce
alerce_client = Alerce()
tde_sample = alerce_client.query_objects(
    classifier='LC_classifier_ATAT_forced_phot(beta)',
    class_name='TDE',
    format='pandas',
    page=1,
    page_size=10
)
```

I'm not sure how fast is this query running, but for a small page size it works.
We haven't run the new classifiers over all the database, so we don't have TDE candidates older than 2024 yet.

**Comment by LydiaMak** [comment]
Great! Thank you for your reply!

Do you know if there is a plan to run it over all the database?

**Comment by ignacioreyes** [comment]
It's in our plans, but I don't think it will be available before the 1st quarter of 2025
