### ISSUE TITLE
exporting the force photometry 

### ISSUE THREAD

**Issue by svalenti** [alercebroker/alerce_client#44]
Hi, 
I'm trying to export the photometry from alerce of specific object programmatically. I can export detection and non detection using the command
LC = client.query_lightcurve(oid, format='json')

However, I would like to export the force photometry, maybe that is already possible and I just don't find a way of doing it, 

thanks

**Comment by AlxEnashi** [comment]
The client has been updated for some time (since the closing of the issue) but we has some trouble publishing the documentationt.

Now we consider the feature complete and the documentation to use it is [here](https://github.com/alercebroker/alerce_client/issues/44)
